### ISSUE TITLE
can't find my list

### ISSUE THREAD

**Issue by Karechta** [TehNut/AniMouto#18] opened 2019-12-17 13:00 UTC
I have this issue since a few days, where animouto cant find my Anilist. It doesnt show my current progress of watching and airing anime, instead a red message "I tried my best but couldn't find your list".
The rest of the features seem to work.

**Comment by Karechta** [comment] 2019-12-18 06:34
Bananya was the issue

**Comment by TehNut** [comment] 2019-12-18 06:36
Duplicate of [this comment tree](https://anilist.co/forum/thread/7424/comment/226935) but now it's here so I can remember it exists 👍

**Comment by TehNut** [comment] 2019-12-18 06:51
Fixed in 2.0.14 which should be live soon

**Closed by TehNut** 2019-12-18 06:51 UTC
Labels: awaiting release, bug
