### ISSUE TITLE
Forgets log-in randomly on Firefox

### ISSUE THREAD

**Issue by Silver-Fullbuster** [TehNut/AniMouto#30] opened 2020-09-09 18:48 UTC
The extension sometimes forgets my login after every few days. I use Firefox heavily so it's rare in terms of the number of times I open Firefox, but every few days it randomly forgets it.

Firefox x64 v80.0.1 on Windows 10 v1909
AniMouto v2.0.21

**Comment by TehNut** [comment] 2020-09-09 18:53
Duplicate of #28

**Closed by TehNut** 2020-09-09 18:53 UTC
